from enum import StrEnum


class IkeEventName(StrEnum):
    IKE_START = "IKE_START"
    IKE_SA_INIT_START = "IKE_SA_INIT_START"
    IKE_SA_INIT_COMPLETE = "IKE_SA_INIT_COMPLETE"
    MLKEM_START = "MLKEM_START"
    MLKEM_COMPLETE = "MLKEM_COMPLETE"
    IKE_AUTH_START = "IKE_AUTH_START"
    IKE_AUTH_COMPLETE = "IKE_AUTH_COMPLETE"
    IKE_SA_ESTABLISHED = "IKE_SA_ESTABLISHED"
    CHILD_SA_INSTALLED = "CHILD_SA_INSTALLED"
    REKEY_START = "REKEY_START"
    REKEY_COMPLETE = "REKEY_COMPLETE"
    SA_DELETED = "SA_DELETED"
    IKE_FAILURE = "IKE_FAILURE"

