charon {
    load_modular = yes

    filelog {
        stderr {
            default = 1
            ike = 1
            net = 1
            flush_line = yes
        }
    }

    plugins {
        include strongswan.d/charon/*.conf
    }
}

include strongswan.d/*.conf

