connections {
    m3-hybrid {
        version = 2
        local_addrs = 10.10.0.1
        remote_addrs = 10.10.0.2
        proposals = aes256gcm16-prfsha384-x25519-ke1_mlkem768
        mobike = no
        reauth_time = 0

        local {
            auth = psk
            id = ric
        }
        remote {
            auth = psk
            id = du
        }

        children {
            e2 {
                mode = transport
                local_ts = 10.10.0.1/32
                remote_ts = 10.10.0.2/32
                esp_proposals = aes256gcm16-noesn
                start_action = none
                rekey_time = 0
            }
        }
    }
}

